site_name: PSRemotely Docs
repo_url: https://github.com/DexterPOSH/PSRemotely
theme: readthedocs
pages:
  - Home: index.md
  - PSRemotely Basics:
    - Quick Start: Quick-Start-Installation-and-Example.md
    - PSDeploy Configuration Files: PSRemotely-Configuration-Files.md
    - PSRemotely variable: PSRemotely-Remotely-Variable.md
    - PSRemotely workflow: PSRemotely-workflow.md
  - PSRemotely Examples:
    - Basic : Example-Basic.md
    - Using Configuration Data : Example-ConfigurationData.md
    - Using Credential Hashtable: Example-CredentialHash.md
    - Using Configuration Data and Credential : Example-ConfigurationData-Credential.md
    - Using custom Variables : Example-Custom-Variables.md
    - Using IPv4 Address for node name : Example-IPv4-Address.md
    - Using IPv6 Address for node name : Example-Ipv6-Address.md
    - Using PreferNodeProperty parameter : Example-PreferNodeProperty.md
  - How Do I...:
    - Target different types of Nodes in a solution: PSRemotely-Node-Based-Target.md
    - Invoke PSRemotely: Invoke-PSRemotely.md
    - TroubleShoot : PSRemotely.TroubleShoot.md
    - Copy Artifacts to PSRemotely Nodes: PSRemotely.Artifacts.md
    - Re run a failed test: PSRemotely.ReRunTest.md
  - Advanced:
    - Using PoshSpec with PSRemotely: PSRemotely-PoshSpec.md
